logo_title: 杂谈漫话小铺

style: black

favicon: /favicon.ico

menu:
  作品: /project
  域名: /domain
  友联: /links
  关于: /about
  Github: https://github.com/DanileLxp

# 做了域名限制，请改成自己的 KEY
valine:
  appId: SyPFl5QJlrHYGrXmVt1CaBIo-gzGzoHsz
  appKey: NgKaTKuBzo89McqUkTPaI38q

highlight:
  enable: false
